- app/models/participant.rb
- app/views/devise/registrations/new.html.erb
- spec/models/participant_spec.rb
> Display Name regex added

- app/concepts/leaderboard/cells/table_row.rb
- app/concepts/leaderboard/views/baseline_row.erb
- app/concepts/leaderboard/views/table_row.erb
> simple fix for baseline leaderboard fix in view layer, does not alter DB

- CONTRIBUTING.md
- PREREQUISITES.md
> Tweaks in docs

- app/admin/challenge.rb
- app/assets/javascripts/controllers/challenges_controller.js
- app/controllers/challenges_controller.rb
- app/policies/challenge_policy.rb
- app/views/challenges/reorder.html.erb
- config/routes.rb
Overall this is pretty good @mridulnagpal .  We need to add a link to it somewhere and my suggestion is under the admin interface which uses ActiveAdmin.  Why don't you see if you can add a batch action for challenges (https://activeadmin.info/9-batch-actions.html)
> reorder challenges via drag-and-drop (work in progress)

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/concepts/leaderboard/cell.rb
- app/concepts/leaderboard/views/baseline_row.erb
- app/concepts/leaderboard/views/submission_rows.erb
- app/concepts/leaderboard/views/table_head.erb
- app/concepts/leaderboard/views/table_row.erb
- app/views/articles/_masthead.html.erb
- app/views/blogs/_blog_post.html.erb
@mridulnagpal : Here is a working demo with local-time in a cell.
> example using local-time

- app/assets/stylesheets/_header.scss
- app/assets/stylesheets/_layout-atoms.scss
Pulls in fixes by @yannis from https://github.com/crowdAI/crowdai/commit/1d6477a8a9478d69be5eb2e724e7b2c3c97c5220 and https://github.com/crowdAI/crowdai/commit/30e2799a9264ee3ea819d1a6bb238155d63a1a23
> Fixes #759 - Use asset-url instead of url for correct resolution of asset links

- app/models/participant.rb
- spec/models/participant_spec.rb
> Username improved

- app/assets/stylesheets/_responsive-iframe.scss
- app/assets/stylesheets/application.css.scss
- app/controllers/challenges_controller.rb
- app/javascript/react_components/index.js
- app/views/challenges/form/_dynamic_content.html.erb
- app/views/dynamic_contents/index.html.erb
- db/migrate/20190111110530_add_dynamic_content_url_to_challenges.rb
- db/schema.rb
> custom challenge components

- app/mailers/admin/challenge_call_response_notification_mailer.rb
- app/mailers/admin/organizer_application_notification_mailer.rb
- app/mailers/admin/submission_notification_mailer.rb
- app/mailers/application_mailer.rb
- app/mailers/comment_notification_mailer.rb
- app/mailers/devise_mandrill_mailer.rb
- app/mailers/email_digest_mailer.rb
- app/mailers/gdpr_export_mailer.rb
- app/mailers/leaderboard_notification_mailer.rb
- app/mailers/organizer/eua_notification_mailer.rb
- app/mailers/organizer_application_notification_mailer.rb
- app/mailers/submission_graded_notification_mailer.rb
- app/mailers/topic_notification_mailer.rb
- spec/factories/mandrill_message_factory.rb
- spec/helpers/mandrill_spec_helper.rb
- spec/mailers/email_digest_mailer_spec.rb
- spec/models/mandrill_message_spec.rb
> Updated from email, subject and content of mailer (#782)

- app/views/doorkeeper/authorizations/new.html.erb
s/crowdai.org/aicrowd.com/g
s/crowdAI/AIcrowd/g
> Modify stale org name and http references in OAuth authorization template

- CONTRIBUTING.md
- config/application.rb
- config/application.yml.example
- config/environments/development.rb
- config/environments/test.rb
- config/initializers/aws.rb
> carrierwave local uploads (#785)

- app/admin/success_story.rb
- app/assets/stylesheets/application-redesign.css.scss
- app/concepts/image/cell.rb
- app/controllers/success_stories_controller.rb
- app/models/success_story.rb
- app/policies/success_story_policy.rb
- app/views/layouts/_header.html.erb
- app/views/success_stories/_success_story_post.html.erb
- app/views/success_stories/index.html.erb
- app/views/success_stories/show.html.erb
- config/routes.rb
- db/migrate/20190317081611_create_success_stories.rb
- db/migrate/20190317100125_fix_success_stories.rb
- db/migrate/20190317103012_add_logo_to_success_stories.rb
- db/schema.rb
- db/seeds.rb
- db/seeds/success_stories/success_stories.rb
- spec/controllers/success_stories_controller_spec.rb
- spec/factories/success_stories.rb
- spec/models/success_story_spec.rb
Added success stories mechanism
> Success stories

- doc/grading_overview.md
> crowdAI -> AIcrowd

- PREREQUISITES.md
> missing ; at the end of CREATE DATABASE

- app/assets/javascripts/controllers/challenges_controller.js
- app/controllers/participants_controller.rb
- app/views/leaderboards/index.html.erb
@spMohanty please check my comments in both the issues and confirm if the way I am handling is the desired way.
Main discussion points: Do we wrap the note in class=update or have the challenge organizers add it to the markdown manually?
When a participant tries to access /participants do we redirect to the home page or somewhere else?
> Leaderboard Note and 500 on /participants

- app/admin/team_members.rb
- app/controllers/team_members_controller.rb
- app/models/team_member.rb
- app/views/layouts/_footer.html.erb
- app/views/layouts/_header.html.erb
- app/views/team_members/index.html.erb
- config/routes.rb
- db/migrate/20190810133044_create_team_members.rb
- db/schema.rb
- spec/controllers/team_members_controller_spec.rb
- spec/factories/team_member_factory.rb
- spec/models/team_member_spec.rb
Most of the things are done.
Pending: 
- Some Text that needs changing
- ~Tests~
> [WIP] Our Team Page 

- app/services/grader_service.rb
Closes https://github.com/AIcrowd/AIcrowd/issues/1008
> Grader Service: Send Team ID if present

- app/concepts/participant_clef_task/views/list_detail.erb
- app/concepts/participant_clef_task/views/participant_submitted.erb
- app/concepts/participant_clef_task/views/participant_unregistered.erb
- app/concepts/participant_clef_task/views/profile_incomplete.erb
- app/controllers/api/base_controller.rb
- app/controllers/api/old_submissions_controller.rb
- app/controllers/api/submissions_controller.rb
- app/mailers/organizer/eua_notification_mailer.rb
- app/views/challenges/clef_task.html.erb
- app/views/challenges/show/_subnav.html.erb
- app/views/clef_tasks/_form.html.erb
- app/views/clef_tasks/edit.html.erb
- app/views/clef_tasks/index.html.erb
- app/views/clef_tasks/new.html.erb
- app/views/clef_tasks/show.html.erb
- app/views/members/_members.html.erb
- app/views/organizers/_form.html.erb
- app/views/organizers/_subnav.html.erb
- app/views/submissions/new.html.erb
- app/views/submissions/new/_clef_form.html.erb
- app/views/task_dataset_files/index.html.erb
- app/views/task_dataset_files/new.html.erb
- config/routes.rb
- db/seeds/clef/clef.rb
- package-lock.json
Implemented the following:
- Organizer edit page => Can choose if CLEF organizer
- ( Note: If challenge is created by CLEF organizer, clef_challenge field in challenge table is set to true)
- db/seeds/clef/clef.rb  in order to get started quickly with CLEF related stuff (I ran: rails runner -e development db/seeds/clef/clef.rb)
- Possibility to show/create/edit tasks on organizer page (Tasks tab), only active if CLEF organizer 
- (Note: A task is an umbrella for CLEF challenges that share the same dataset)
- (Note: dataset files are added to the table task_dataset_files)
- On the show task page, dataset files can be added
==> PROBLEM: there seems a problem with adding dataset files, the dataset_file_s3_key does not seem to be added to the db
- (Note: End User Agreement (EUA) PDF template …
> Implement Adjustments for CLEF

- app/concepts/leaderboard/cell.rb
- app/concepts/leaderboard/cells/table_row.rb
- app/concepts/leaderboard/views/baseline_row.erb
- app/concepts/leaderboard/views/table_row.erb
- app/concepts/submission/cell.rb
- app/concepts/submission/cells/submission_detail.rb
- app/concepts/submission/views/table_row.erb
- app/services/calculate_leaderboard_service.rb
- spec/services/calculate_leaderboard_ordering_spec.rb
This commit refactors the Leaderboard Calculation Service to properly
handle the orders that are defined into the challenge.
Also refactors the submission detail and submission list views
to show the correct formatted value.
> Leaderboard Calculation: Order Refactor \& Submission views formatting

- app/concepts/leaderboard/cell.rb
https://rollbar.com/aicrowd-production/aicrowd-production/items/201
> Leaderboard View: Fix bug in leaderboard view causing 500s

- app/concepts/participant_clef_task/views/list_detail.erb
- app/views/challenges/clef_task.html.erb
- db/schema.rb
Fixes #1034 
Only Html adoptions made to clef specific views. Should be safe to merge.
Result:
> Fix participants view for clef challenges

- app/concepts/participant_clef_task/views/participant_submitted.erb
- app/concepts/participant_clef_task/views/participant_unregistered.erb
- app/concepts/participant_clef_task/views/profile_incomplete.erb
- db/schema.rb
@nemaniarjun 
This PR fixes some broken views for the CLEF EUA workflow. This only affects clef-specific views and does not interfere with anything else in the system, so it's safe to merge.
> Fix views related to EUA workflow for CLEF

- .hound
- .travis.yml
Based On: https://docs.codeclimate.com/docs/travis-ci-test-coverage
> Travis: Add code coverage with CodeClimate

- app/models/login_activity.rb
- db/migrate/20200117111958_remove_login_activities_table.rb
- db/schema.rb
> Remove LoginActivity model

- app/helpers/team_helper.rb
- spec/controllers/dataset_files_controller_spec.rb
- spec/factories/challenge_factory.rb
- spec/factories/challenge_participant_factory.rb
- spec/factories/participant_factory.rb
- spec/factories/team_participant_factory.rb
- spec/features/challenges_controller_spec.rb
https://rollbar.com/aicrowd-production/aicrowd-production/items/244/
I'll write test coverage tomorrow.
> Fix undefined my_team variable for TeamHelper

- app/admin/partner.rb
Rollbar:
https://rollbar.com/aicrowd-production/aicrowd-production/items/249/
> Fix nil exceptions in active-admin partner pages

- app/assets/stylesheets/challenges/form.scss
- app/concepts/image/cell.rb
- app/controllers/challenges_controller.rb
- app/uploaders/image_uploader.rb
- app/views/challenges/remove_image.js.erb
- app/views/challenges/tabs/_details_form.html.erb
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/429632970
> Remove Challenge Card Image through ajax request

- app/controllers/participant_clef_tasks_controller.rb
- spec/requests/participant_clef_tasks_controller_spec.rb
Rollbar:
https://rollbar.com/aicrowd-production/aicrowd-production/items/254/
> Fix nil exception in participant_clef_tasks#create action

- db/migrate/20200210143323_create_challenge_stats_materialized_view.rb
- db/schema.rb
- db/views/challenge_stats_v01.sql
It turns out this view is actually used in ActiveAdmin panel:
https://github.com/AIcrowd/AIcrowd/blob/master/app/admin/challenge_stat.rb
> Create ChallengeStats materialised view

- app/controllers/api/base_controller.rb
- app/controllers/api/clef_tasks_controller.rb
- app/controllers/api/external_graders_controller.rb
- app/controllers/api/old_submissions_controller.rb
- app/controllers/api/submissions_controller.rb
- app/controllers/application_controller.rb
- app/controllers/blogs_controller.rb
- app/controllers/challenge_rules_controller.rb
- app/controllers/challenges/team_invitations_controller.rb
- app/controllers/challenges/teams_controller.rb
- app/controllers/invitations_controller.rb
- app/controllers/job_postings_controller.rb
- app/controllers/participants_controller.rb
- app/controllers/participation_terms_controller.rb
- app/controllers/success_stories_controller.rb
- app/controllers/team_invitations/acceptances_controller.rb
- app/controllers/team_invitations/cancellations_controller.rb
- app/controllers/team_invitations/claim_emails_controller.rb
- app/controllers/team_invitations/declinations_controller.rb
- app/controllers/teams_controller.rb
Use private section for methods that are not used outside of class.
Link : https://aicrowd.monday.com/boards/363093650/pulses/420516667
> Move methods that are not used outside of class to private section in app/controllers folder

- app/helpers/leaderboard_helper.rb
- app/mailers/organizer/eua_notification_mailer.rb
- app/views/challenges/index.js.erb
- app/views/clef_tasks/_task_dataset_file.html.erb
- app/views/clef_tasks/show.html.erb
- app/views/leaderboards/_leaderboards.html.erb
- app/views/shared/challenges/_media.html.erb
- app/views/submissions/_submissions.html.erb
- spec/features/clef_tasks_controller_spec.rb
- spec/features/leaderboards_controller_spec.rb
- spec/features/submissions_controller_spec.rb
Rollbar errors:
https://rollbar.com/aicrowd-production/aicrowd-production/items/255/
https://rollbar.com/aicrowd-production/aicrowd-production/items/256/
https://rollbar.com/aicrowd-production/aicrowd-production/items/257/
https://rollbar.com/aicrowd-production/aicrowd-production/items/259/
https://rollbar.com/aicrowd-production/aicrowd-production/items/260/
https://rollbar.com/aicrowd-production/aicrowd-production/items/261/
https://rollbar.com/aicrowd-production/aicrowd-production/items/262/
> Fix exceptions on submissions and leaderboard pages

- app.json
> Fix database setup for review apps

- app/controllers/challenges_controller.rb
- app/models/challenge.rb
- app/policies/challenge_policy.rb
- app/views/challenges/tabs/_admin_form.html.erb
- config/routes.rb
- spec/requests/challenges_controller_spec.rb
Monday ticket:
https://aicrowd.monday.com/boards/363093650/pulses/447286098
Github Issue:
https://github.com/AIcrowd/AIcrowd/issues/788
Blocked until questions in Github Issue gest answered.
> Add Challenge exporting to JSON functionality

- app/helpers/submissions_helper.rb
Rollbar:
https://rollbar.com/aicrowd-production/aicrowd-production/items/264/
> Fix nil exception in submission_view_description(submission) method

- app/views/challenges/show.html.erb
Fix : Blank challenge description fail on show page
https://aicrowd.monday.com/boards/363093650/pulses/467488942
> Add try on description

- app/assets/javascripts/controllers/challenges_controller.js
- app/controllers/challenges_controller.rb
- app/controllers/leaderboards_controller.rb
- app/queries/leaderboards/select_unique_meta_keys_query.rb
- app/services/leaderboards/csv_export_service.rb
- app/views/challenges/_form.html.erb
- app/views/challenges/edit.html.erb
- app/views/challenges/tabs/_admin_form.html.erb
- app/views/challenges/update.js.erb
- config/routes.rb
- spec/queries/leaderboards/select_unique_meta_keys_query_spec.rb
- spec/requests/leaderboards_controller_spec.rb
- spec/services/leaderboards/csv_export_service_spec.rb
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/432235176
Github issue:
https://github.com/AIcrowd/AIcrowd/issues/1088
> Export leaderboards to CSV file

- app/controllers/challenges_controller.rb
It has been changed from 20 to 18 for making to be multiple of 3, so the current design looks good without missing blocks on/before "load more".
> Challenges page size changed

- package.json
- yarn.lock
Downgrade webpack-cli to 3.3.0 version.
> Fix yarn webpack setup

- app/assets/javascripts/controllers/challenges_controller.js
- app/assets/stylesheets/application-redesign.css.scss
- app/javascript/stimulus_js/controllers/prioritynav_controller.js
- app/views/challenges/show/_subnav.html.erb
Moves the P-nav code from Pamola implementation to stimulusjs
to ensure that the code runs on all challenge pages.
> Priority Nav: Trigger on all challenge pages

- app/assets/stylesheets/application-redesign.css.scss
- app/helpers/participants_helper.rb
- app/models/participant.rb
- app/views/participants/_masthead.html.erb
User Rating - Reputation System (Trueskill)
https://aicrowd.monday.com/boards/363093650/pulses/457819177
> User rating reputation system

- app/assets/stylesheets/application-redesign.css.scss
- app/assets/stylesheets/challenges/datatable.scss
- app/assets/stylesheets/challenges/form.scss
- app/javascript/packs/application.js
- app/javascript/stimulus_js/controllers/simple_datatables_controller.js
- app/views/challenges/fields/_invitations_table_fields.html.erb
- package.json
- yarn.lock
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/458107017
Github issue:
https://github.com/AIcrowd/AIcrowd/issues/64
> Add datatables to challenge invitations table

- app/views/challenges/show.html.erb
This PR was created in an impromptu midnight sprint, for prototyping a hacky implementation of features from conception to deployment. 🎉
> Hacky implementation of tabular overview page in challenges

- app/assets/javascripts/controllers/challenges_controller.js
- app/assets/stylesheets/application-redesign.css.scss
- app/assets/stylesheets/challenges/datatable.scss
- app/assets/stylesheets/challenges/form.scss
- app/controllers/challenges_controller.rb
- app/javascript/packs/application.js
- app/javascript/stimulus_js/controllers/simple_datatables_controller.js
- app/services/leaderboards/csv_export_service.rb
- app/services/submissions/csv_export_service.rb
- app/views/challenges/fields/_challenge_round_fields.html.erb
- app/views/challenges/fields/_invitations_table_fields.html.erb
- app/views/challenges/fields/_submit_buttons.html.erb
- app/views/challenges/show.html.erb
- app/views/challenges/tabs/_admin_form.html.erb
- app/views/challenges/tabs/_details_form.html.erb
- app/views/challenges/tabs/_overview_form.html.erb
- app/views/challenges/tabs/_private_challenge_form.html.erb
- app/views/challenges/tabs/_rounds_form.html.erb
- app/views/challenges/tabs/_rules_form.html.erb
- app/views/challenges/tabs/_submissions_form.html.erb
- app/views/challenges/tabs/_winner_form.html.erb
- app/views/challenges/update.js.erb
- package.json
- spec/features/challenges_controller_spec.rb
- spec/services/leaderboards/csv_export_service_spec.rb
- spec/services/submissions/csv_export_service_spec.rb
- yarn.lock
Rake tasks that we need to run after release:
> Release 28.02.20 Release

- app/assets/javascripts/controllers/challenges_controller.js
- app/views/challenges/show.html.erb
* Mobile rendering issue is now fixed
* Page resizes trigger rendering
Original PR for approval exist at #1190
> Hotfix: Tabular overview page bugfixes and moved code to controller

- app/policies/challenge_policy.rb
- app/views/challenges/show/_subnav.html.erb
- app/views/leaderboards/index.html.erb
- app/views/submissions/index.html.erb
Closes https://github.com/AIcrowd/AIcrowd/issues/1180
> Challenge Subnav: Reorder Tabs & Add show policies

- app/views/leaderboards/index.html.erb
Rollbar: 
https://rollbar.com/aicrowd-production/aicrowd-production/items/276/
> Fix nil exception on @current_round in leaderboards#index

- app/controllers/participants_controller.rb
- app/helpers/discourse_helper.rb
- app/services/discourse/create_category_service.rb
- app/services/discourse/fetch_user_posts_service.rb
- app/services/discourse/update_category_service.rb
- app/views/participants/_discourse_posts_list.html.erb
- app/views/participants/show.html.erb
- config/application.yml.example
- spec/rails_helper.rb
- spec/services/discourse/create_category_service_spec.rb
- spec/services/discourse/fetch_user_posts_service_spec.rb
- spec/services/discourse/update_category_service_spec.rb
- spec/vcr/discourse_api/create/success.yml
- spec/vcr/discourse_api/create/success_generated_new_category_name.yml
- spec/vcr/discourse_api/create/success_truncated_category_name.yml
- spec/vcr/discourse_api/data_explorer_queries/user_posts/success.yml
- spec/vcr/discourse_api/update/success.yml
- spec/vcr/discourse_api/update/success_generated_new_category_name.yml
- spec/vcr/discourse_api/update/success_truncated_category_name.yml
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/474972252
> Display Discourse posts on Posts tab

- app/views/landing_page/index.html.erb
- app/views/layouts/_footer.html.erb
Removing the dependency of having Discourse set up, some views are breaking otherwise
> Bugfix: Development environment breaking when discourse not setted up

- app/admin/challenge_call.rb
- app/jobs/admin/challenge_call_response_notification_job.rb
- app/mailers/admin/challenge_call_response_notification_mailer.rb
- config/routes.rb
- db/migrate/20200305150815_add_acknowledged_to_challenge_call.rb
- db/schema.rb
Call for challenge form minor improvements
https://aicrowd.monday.com/boards/363093650/pulses/474943048
> Add acknowledged and send challenge call to organizer

- app/assets/stylesheets/application-redesign.css.scss
- app/views/leaderboards/_leaderboards.html.erb
Github issue:
https://github.com/AIcrowd/AIcrowd/issues/1215
> Fix View button in leaderboards listing

- app/assets/stylesheets/application-redesign.css.scss
- app/views/participants/_challenge_list.html.erb
- app/views/rating_leaderboard/index.html.erb
Based on views rendered on staging
> Bugfix in rating displays

- app/assets/stylesheets/application-redesign.css.scss
- app/views/challenges/discussions/show.html.erb
- app/views/landing_page/_discourse_top_contributors.html.erb
- app/views/participants/_discourse_posts_list.html.erb
- app/views/shared/discourse/_topics_list.html.erb
> User tooltip rendering in Discourse views

- db/schema.rb
After previous release db/schema.rb file got corrupted. I’ve recreated it from migrations.
> Fix db/schema.rb file

- app/controllers/email_preferences_controller.rb
- app/views/email_preferences/_form.html.erb
- db/migrate/20200319083607_add_agreed_to_organizers_newsletter_to_participants.rb
- db/schema.rb
- spec/factories/participant_factory.rb
- spec/features/email_preferences_controller_spec.rb
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/497879421
> Add unsubscribe from organizers newsletter functionality

- app/controllers/rating_leaderboard_controller.rb
- app/controllers/user_rating_controller.rb
- app/queries/participant_rating_ranks_query.rb
- app/services/user_rating_service.rb
- app/views/shared/_load_more.html.erb
Fix for rollbar issues for rating system.
> fixing the rollbar issues

- app/controllers/participants_controller.rb
Fixing Not found on user pages:
http://localhost:3000/participants/MTab
> fixing participant not found issue

- app/controllers/members_controller.rb
Fix for closed PR https://github.com/AIcrowd/AIcrowd/pull/1250
> quick fix for delete member to organisation

- app/models/team.rb
- app/policies/team_policy.rb
Bug reported by @jyotishp and email from participant.
> Bugfix: Fixed wrong logic to check for full teams

- app.json
- config/environments/staging.rb
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/504714711
> Fetch assets from server for review apps

- app/policies/ongoing_leaderboard_policy.rb
Rollbar: 
https://rollbar.com/aicrowd-production/aicrowd-production/items/294/
> Fix broken ongoing_leaderboards SQL query

- app/admin/newsletter_email.rb
- app/assets/stylesheets/application-redesign.css.scss
- app/controllers/challenges/newsletter_emails_controller.rb
- app/forms/newsletter_email_form.rb
- app/models/newsletter_email.rb
- app/models/participant.rb
- app/policies/newsletter_email_form_policy.rb
- app/policies/newsletter_email_policy.rb
- app/validators/emails_list_validator.rb
- app/views/challenges/newsletter_emails/new.html.erb
- app/views/shared/challenges/_masthead.html.erb
- config/routes.rb
- db/migrate/20200323162149_update_newsletter_emails_fields.rb
- db/schema.rb
- spec/factories/newsletter_email_factory.rb
- spec/features/newsletter_emails_controller_spec.rb
- spec/validators/emails_list_validator_spec.rb
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/498000027
https://aicrowd.monday.com/boards/363093650/pulses/497843324
https://aicrowd.monday.com/boards/363093650/pulses/497913469
> Add send newsletter e-mail action to challenge#show page

- app/admin/newsletter_email.rb
- app/assets/stylesheets/application-redesign.css.scss
- app/assets/stylesheets/challenges/newsletter_email_form.scss
- app/controllers/api/v1/challenges/participants_controller.rb
- app/controllers/api/v1/challenges/teams_controller.rb
- app/controllers/challenges/newsletter_emails_controller.rb
- app/forms/newsletter_email_form.rb
- app/javascript/stimulus_js/controllers/select2_controller.js
- app/models/participant.rb
- app/serializers/api/v1/challenges/search_participants_serializer.rb
- app/serializers/api/v1/challenges/search_teams_serializer.rb
- app/views/challenges/newsletter_emails/new.html.erb
- config/routes.rb
- db/migrate/20200327142425_add_declined_to_newsletter_emails.rb
- db/schema.rb
- spec/features/admin/newsletter_email_spec.rb
- spec/requests/api/v1/challenges/participants_controller_spec.rb
- spec/requests/api/v1/challenges/teams_controller_spec.rb
- spec/serializers/api/v1/challenges/search_participants_serializer_spec.rb
- spec/serializers/api/v1/challenges/search_teams_serializer_spec.rb
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/497849368
Documentation:
https://select2.org/data-sources/ajax
> Add Users multiselect search dropdown to NewsletterEmailForm

- app/admin/newsletter_email.rb
- app/jobs/organizers/newsletter_email_job.rb
- app/mailers/application_mailer.rb
- app/mailers/organizers/newsletter_email_mailer.rb
- spec/features/admin/newsletter_email_spec.rb
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/497868345
Documentation:
https://mandrillapp.com/api/docs/messages.JSON.html#method=send
> Add Organizer::NewsletterEmailMailer and queue it after admin approve

- app/assets/javascripts/controllers/challenges_controller.js
- app/controllers/challenges_controller.rb
- app/helpers/challenges_helper.rb
- app/views/challenges/tabs/_details_form.html.erb
Create new category to challenge/edit
https://aicrowd.monday.com/boards/363093650/pulses/499058864
> Create category tag to challenge form

- app/controllers/api/v1/challenges/newsletter_emails_controller.rb
- app/javascript/stimulus_js/controllers/newsletter_email_form_controller.js
- app/javascript/stimulus_js/controllers/select2_controller.js
- app/jobs/organizers/newsletter_email_job.rb
- app/jobs/organizers/preview_newsletter_email_job.rb
- app/mailers/organizers/newsletter_email_mailer.rb
- app/views/challenges/newsletter_emails/new.html.erb
- config/routes.rb
- spec/requests/api/v1/challenges/newsletter_emails_controller_spec.rb
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/508709211
> Add Preview NewsletterEmail functionality

- config/initializers/session_store.rb
Had to revert back session_store.rb changes related to share subdomain session. Because getting issue with login feature.
> fix participant login

- app/javascript/stimulus_js/controllers/challenge_overview_controller.js
We want to disable tabular view which was recently added based on feedback from multiple users
> Reverted tabular table of content

- app/views/leaderboards/_leaderboards.html.erb
> Fix leaderboard rendering for single person team 

- app/helpers/meta_tags_helper.rb
https://aicrowd.monday.com/boards/363093650/pulses/517801550
> Set header for challenge tab

- app/views/rating_leaderboard/index.html.erb
> Adding blog link in the leaderboard page

- app/controllers/api/v1/base_controller.rb
- app/controllers/api/v1/challenges/challenge_rounds_controller.rb
- app/controllers/challenges_controller.rb
- app/javascript/stimulus_js/controllers/challenge_rounds_controller.js
- app/javascript/stimulus_js/controllers/newsletter_email_form_controller.js
- app/javascript/stimulus_js/helpers/alerts_helper.js
- app/javascript/stimulus_js/helpers/buttons_helper.js
- app/models/challenge.rb
- app/models/challenge_round.rb
- app/views/challenges/fields/_challenge_round_fields.html.erb
- config/routes.rb
- spec/requests/api/v1/challenges/challenge_rounds_controller_spec.rb
Unfortunately `accept_nested_attributes` doesn't work with `before_destroy` nor `dependent:` options. For this reason I had to implement front-end solution for this issue.
Related Rails issue:
https://github.com/rails/rails/issues/31444
After fix:
> Fix challenge_round removal

- app/controllers/api/v1/challenges/challenge_rounds_controller.rb
- app/serializers/api/v1/challenge_round_serializer.rb
- config/routes.rb
- spec/rails_helper.rb
- spec/requests/api/v1/challenges/challenge_rounds_controller_spec.rb
- spec/serializers/api/v1/challenge_round_serializer_spec.rb
- spec/support/shared_examples/api_v1_authentication_spec.rb
Monday: 
https://aicrowd.monday.com/boards/363093650/pulses/528881721
> Add Api::V1::Challenges::ChallengeRoundsController#create and #update endpoints

- app/assets/stylesheets/application-redesign.css.scss
- app/controllers/challenges_controller.rb
- app/javascript/stimulus_js/controllers/challenge_overview_controller.js
- app/models/concerns/challenges/import_constants.rb
- app/views/challenges/fields/_fancy_radio.html.erb
- app/views/challenges/show.html.erb
- app/views/challenges/tabs/_overview_form.html.erb
- db/migrate/20200414144802_add_tabular_overview_to_challenges.rb
- db/schema.rb
Monday: 
https://aicrowd.monday.com/boards/363093650/pulses/529079050
> Allow to choose which way tabs are displayed on Overview page

- app/controllers/application_controller.rb
> #1347: Fixed login redirection via application controller

- app/helpers/meta_tags_helper.rb
https://aicrowd.monday.com/boards/363093650/pulses/523049035
submission tag with ID :
Default image path :
> More Changes to tags on challenge pages

- app/helpers/challenges_helper.rb
- app/helpers/sanitization_helper.rb
- app/views/challenges/tabs/_details_form.html.erb
- app/views/shared/challenges/_filter.html.erb
- app/views/shared/challenges/_listing.html.erb
- app/views/shared/challenges/_masthead.html.erb
Challenge category rendering fix, prefix hash everywhere. (rename category feature to tags)
Challenge edit page :
Challenge show page :
> Prefix Hash and change category to tags

- app/views/leaderboards/_leaderboards.html.erb
https://aicrowd.monday.com/boards/363093650/pulses/527315773
> Fix issue of undefine team

- app/helpers/challenges_helper.rb
> Sanitize HTML entities from challenge round close time

- app/admin/newsletter_email.rb
- app/assets/stylesheets/additional_active_admin.css.scss
> Allow to edit newsletter_emails in ActiveAdmin

- app/services/discourse/base_service.rb
- app/services/discourse/create_group_service.rb
- db/migrate/20200416205250_add_discourse_group_id_to_challenges.rb
- db/schema.rb
- spec/services/discourse/create_group_service_spec.rb
- spec/vcr/discourse_api/groups/create/success.yml
- spec/vcr/discourse_api/groups/create/success_generated_new_group_name.yml
- spec/vcr/discourse_api/groups/create/success_truncated_group_name.yml
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/522768303
> Add Discourse::CreateGroupService

- app/services/discourse/base_service.rb
- app/services/discourse/create_category_service.rb
- app/services/discourse/create_group_service.rb
- app/services/discourse/fetch_badges_meta_service.rb
- app/services/discourse/fetch_badges_service.rb
- app/services/discourse/fetch_challenge_topics_service.rb
- app/services/discourse/fetch_latest_topics_service.rb
- app/services/discourse/fetch_top_contributors_service.rb
- app/services/discourse/fetch_user_posts_service.rb
- app/services/discourse/update_category_service.rb
- config/initializers/merit.rb
- spec/services/discourse/create_category_service_spec.rb
- spec/services/discourse/create_group_service_spec.rb
- spec/services/discourse/fetch_challenge_topics_service_spec.rb
- spec/services/discourse/fetch_latest_topics_service_spec.rb
- spec/services/discourse/fetch_top_contributors_service_spec.rb
- spec/services/discourse/fetch_user_posts_service_spec.rb
- spec/services/discourse/update_category_service_spec.rb
- spec/support/shared_examples/discourse_service_object_spec.rb
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/535218711
> Remove duplicated code from Discourse ServiceObject classes

- app/services/discourse/add_users_to_group_service.rb
- app/services/discourse/api_client.rb
- spec/services/discourse/add_users_to_group_service_spec.rb
- spec/vcr/discourse_api/add_users_to_group/failure_username_already_part_of_the_group.yml
- spec/vcr/discourse_api/add_users_to_group/failure_username_does_not_exist_in_discourse.yml
- spec/vcr/discourse_api/add_users_to_group/success.yml
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/523058269
> Add Discourse::AddUsersToGroupService

- app/policies/participant_challenge_policy.rb
Rollbar:
https://rollbar.com/aicrowd-production/aicrowd-production/items/308/
> Fix organizer_id Rollbar error

- app/controllers/participants_controller.rb
- app/policies/participant_challenge_policy.rb
Rollbar:
https://rollbar.com/aicrowd-production/aicrowd-production/items/309/
> Fix incorrect LEFT_JOIN query for participant_challenges

- app/models/challenge.rb
- app/models/concerns/challenges/import_constants.rb
- app/serializers/export/category_challenge_serializer.rb
- app/serializers/export/challenge_serializer.rb
- app/serializers/export/challenges_organizer_serializer.rb
- spec/serializers/export/category_challenge_serializer_spec.rb
- spec/serializers/export/challenges_organizer_serializer_spec.rb
Recently I've received request to add categories to challenge export/import.
> Add categories and organizers to challenge export and import

- app/admin/blog.rb
- app/admin/challenge_call.rb
- app/admin/job_posting.rb
- app/admin/participation_terms.rb
- app/assets/stylesheets/ckeditor.scss
Ck Editor Ui fix and fix for `ul` `ol` list
> Fix Ui of CKeditor for admin also fix ul element

- app/controllers/challenges_controller.rb
- app/models/organizer.rb
- app/views/challenges/show.html.erb
- app/views/shared/challenges/_masthead.html.erb
> Render sponsor logos in challenge overview

- app/assets/stylesheets/application-redesign.css.scss
- app/controllers/challenges_controller.rb
- app/models/challenge.rb
- app/services/discourse/fetch_baseline_tag_service.rb
- app/views/challenges/discussions/_discussion_list.html.erb
- app/views/challenges/discussions/show.html.erb
- app/views/challenges/show.html.erb
- app/views/challenges/show/_baseline_discussions.html.erb
- app/views/challenges/show/_sidenav.html.erb
- spec/rails_helper.rb
- spec/services/discourse/fetch_baseline_tag_service_spec.rb
- spec/vcr/discourse_api/baseline_tag/success.yml
https://aicrowd.monday.com/boards/363093650/pulses/522785861
> Add service to get baseline discourse and show on challenge overview

- app/controllers/challenges_controller.rb
- app/models/challenge.rb
- app/views/challenges/show.html.erb
- app/views/challenges/show/_latest_five_submissions.html.erb
- app/views/challenges/show/_sidenav.html.erb
- app/views/challenges/show/_top_five_leaderboards.html.erb
- app/views/leaderboards/_leaderboards.html.erb
- app/views/leaderboards/index.html.erb
- app/views/submissions/_submissions.html.erb
- app/views/submissions/_time_toggle.html.erb
- app/views/submissions/index.html.erb
> Add top five contributors

- app/controllers/api/v1/challenges/challenges_controller.rb
- config/routes.rb
- spec/requests/api/v1/challenges/challenges_controller_spec.rb
https://aicrowd.monday.com/boards/363093650/pulses/522766588
Expose challenge Masterhead as API
> Return masthead partial

- app/controllers/api/v1/participants_controller.rb
- app/helpers/participants_helper.rb
- app/javascript/stimulus_js/controllers/participants_controller.js
- app/views/blogs/_blog_post.html.erb
- app/views/blogs/show.html.erb
- app/views/challenges/_clef_participants.html.erb
- app/views/challenges/discussions/_discussion_list.html.erb
- app/views/challenges/teams/_member_list.html.erb
- app/views/landing_page/_blog_post.html.erb
- app/views/landing_page/_discourse_top_contributors.html.erb
- app/views/landing_page/index.html.erb
- app/views/leaderboards/_leaderboards.html.erb
- app/views/members/_members.html.erb
- app/views/participant_challenges/_participant_challenge_rows.erb
- app/views/participants/_discourse_posts_list.html.erb
- app/views/participants/_get_user_profile.html.erb
- app/views/participants/_name_avatar.html.erb
- app/views/participants/_user_link.html.erb
- app/views/rating_leaderboard/_rating_leaderboard.html.erb
- app/views/shared/discourse/_topics_list.html.erb
- app/views/submissions/_submissions.html.erb
- config/routes.rb
- spec/requests/api/v1/participants_controller_spec.rb
Make the tooltips of users come via API instead of pre-rendered!
Monday : https://aicrowd.monday.com/boards/363093650/pulses/522768696
User tooltip
> get user profile tooltip to API call

- app/views/leaderboards/index.js.erb
Load more button is not working.
issue : `ActionView::Template::Error (undefined local variable or method `sidebar'`
> Fix load more leaderboard button

- app/javascript/stimulus_js/controllers/challenges_controller.js
- app/models/challenge.rb
Bug/ staging - On challenge filter not working properly
> Fix status filter JS and nil, blank prize filter

- app/views/submissions/index.js.erb
> Fix load more button for submissions

- app/jobs/discourse/remove_users_from_group_job.rb
- app/models/challenge_participant.rb
- app/models/challenges_organizer.rb
- app/models/participant_organizer.rb
- app/services/discourse/remove_users_from_group_service.rb
- spec/services/discourse/remove_users_from_group_service_spec.rb
- spec/support/shared_examples/discourse_service_object_spec.rb
- spec/vcr/discourse_api/remove_users_from_group/failure_username_already_out_of_group.yml
- spec/vcr/discourse_api/remove_users_from_group/failure_username_does_not_exist_in_discourse.yml
- spec/vcr/discourse_api/remove_users_from_group/success.yml
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/523062099
> Add Discourse::RemoveUsersFromGroupService

- app/models/concerns/challenges/import_constants.rb
- app/serializers/export/challenge_serializer.rb
- app/services/challenges/import_service.rb
- spec/requests/api/v1/challenges/challenges_controller_spec.rb
- spec/serializers/export/dataset_file_serializer_spec.rb
Recently Ayush have requested the ability to import dataset_files together with challenges.
> Allow to export/import dataset files for challenges

- app/admin/newsletter_email.rb
- app/assets/javascripts/active_admin/newsletter_emails.js
- app/forms/newsletter_email_form.rb
- app/jobs/organizers/declined_email_job.rb
- app/jobs/organizers/newsletter_email_job.rb
- app/mailers/organizers/declined_email_mailer.rb
- app/mailers/organizers/newsletter_email_mailer.rb
- app/models/challenge.rb
- app/models/newsletter_email.rb
- app/policies/newsletter_email_policy.rb
- config/initializers/active_admin.rb
- config/routes.rb
- db/migrate/20200427085949_add_challenge_reference_to_newsletter_emails.rb
- db/migrate/20200427094259_add_decline_reason_to_newsletter_emails.rb
- db/schema.rb
- spec/features/admin/newsletter_email_spec.rb
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/522984872
> Update newsletter_emails feature

- app/controllers/api/v1/challenges/newsletter_emails_controller.rb
- app/forms/newsletter_email_form.rb
- app/javascript/stimulus_js/controllers/newsletter_email_form_controller.js
- app/jobs/admin/newsletter_email_notification_job.rb
- app/mailers/admin/newsletter_email_notification_mailer.rb
- app/mailers/organizers/newsletter_email_mailer.rb
- app/models/participant.rb
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/546557782
> Send newsletter_email notifications to AICrowd admins

- app/controllers/submissions_controller.rb
- app/helpers/tabs_helper.rb
- app/views/submissions/index.html.erb
Rollbar:
https://rollbar.com/aicrowd-production/aicrowd-production/items/275/
https://rollbar.com/aicrowd-production/aicrowd-production/items/320/
> Fix submissions#index page 5xx when challenge does not have active round

- app/assets/stylesheets/application-redesign.css.scss
- app/helpers/challenges_helper.rb
- app/views/challenges/discussions/show.html.erb
- app/views/challenges/show/_baseline_discussions.html.erb
- app/views/challenges/show/_latest_five_submissions.html.erb
- app/views/challenges/show/_sidenav.html.erb
- app/views/challenges/show/_top_five_leaderboards.html.erb
- app/views/leaderboards/_leaderboards.html.erb
- app/views/leaderboards/index.html.erb
- app/views/leaderboards/index.js.erb
- app/views/participants/_name_avatar.html.erb
- app/views/submissions/_submissions.html.erb
- app/views/submissions/index.html.erb
- app/views/submissions/index.js.erb
https://aicrowd.monday.com/boards/363093650/pulses/546946200
> set sidebar with truncate

- app/assets/stylesheets/application-redesign.css.scss
- app/controllers/challenges_controller.rb
- app/controllers/leaderboards_controller.rb
- app/models/challenge.rb
- app/models/concerns/challenges/import_constants.rb
- app/policies/challenge_policy.rb
- app/serializers/export/challenge_serializer.rb
- app/services/challenges/import_service.rb
- app/views/challenges/show/_sidenav.html.erb
- app/views/challenges/tabs/_details_form.html.erb
- app/views/shared/challenges/_masthead.html.erb
- app/views/shared/challenges/_masthead_extra.html.erb
- app/views/shared/challenges/_masthead_pills.html.erb
- config/routes.rb
- db/migrate/20200501225322_add_banner_file_to_challenge.rb
- db/migrate/20200502001504_add_banner_color_to_challenge.rb
- db/schema.rb
Added twitter type banner (image+color) branding for challenges
> Feature/Challenge Banner

- app/admin/setting.rb
- app/assets/stylesheets/application-redesign.css.scss
- app/helpers/application_helper.rb
- app/models/setting.rb
- app/views/layouts/_footer.html.erb
- app/views/layouts/_header.html.erb
- db/migrate/20200428141610_add_banner_to_setting.rb
- db/schema.rb
Monday : https://aicrowd.monday.com/boards/363093650/pulses/545832917
Header
Footer
> manage banner to admin

- app/assets/stylesheets/application-redesign.css.scss
- app/views/shared/challenges/_listing.html.erb
> Remove gap below stats

- app/controllers/challenge_rules_controller.rb
- app/controllers/dataset_files_controller.rb
- app/controllers/submissions_controller.rb
- app/helpers/challenges_helper.rb
- app/views/challenge_rules/show.html.erb
- app/views/challenges/show/_subnav.html.erb
- config/routes.rb
New URL:
https://www.aicrowd.com/challenges/aicrowd-blitz-may-2020/challenge_rules
> Change URL of challenge rules to not require :id

- app/admin/setting.rb
- app/helpers/application_helper.rb
- app/views/layouts/_footer.html.erb
- db/migrate/20200504111847_change_banner_text_to_be_text_in_settings.rb
- db/schema.rb
https://aicrowd.monday.com/boards/363093650/pulses/548562076
> Change banner_text type to admin

- app/assets/stylesheets/application-redesign.css.scss
- app/controllers/api/v1/participants_controller.rb
- app/javascript/stimulus_js/controllers/participants_controller.js
- app/views/challenges/show/_latest_five_submissions.html.erb
- app/views/challenges/show/_top_five_leaderboards.html.erb
- app/views/landing_page/_discourse_top_contributors.html.erb
- app/views/landing_page/index.html.erb
- app/views/leaderboards/_leaderboards.html.erb
- app/views/participants/_get_user_profile.html.erb
- app/views/participants/_name_avatar.html.erb
- app/views/participants/_user_link.html.erb
Fix user tooltip truncate for all place
Monday https://aicrowd.monday.com/boards/363093650/pulses/553970738
> Truncate user name on specific places

- app/controllers/application_controller.rb
- app/controllers/challenge_participants_controller.rb
> Redirect after participants accepts terms to previous page

- app/helpers/challenges_helper.rb
- app/models/challenge.rb
- app/views/shared/challenges/_listing.html.erb
- app/views/shared/challenges/_masthead_extra.html.erb
- app/views/shared/challenges/_team_stat.html.erb
>  Show number of team statistic

- app/views/challenges/show/_sidenav.html.erb
- app/views/challenges/show/_top_five_leaderboards.html.erb
- app/views/leaderboards/_leaderboards.html.erb
- app/views/leaderboards/index.html.erb
> Truncate team name

- app/javascript/stimulus_js/controllers/load_more_controller.js
cc: @alkeshrails to approve/reject PR based on his analysis
> Suggestion: Infinite scroll trigger condition

- app/controllers/dataset_files_controller.rb
- app/views/dataset_files/_form.html.erb
- app/views/dataset_files/edit.html.erb
- app/views/dataset_files/new.html.erb
- app/views/shared/challenges/_dataset_file.html.erb
- db/migrate/20200501103734_add_own_s3_columns_to_dataset_files.rb
- db/schema.rb
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/546486583
> Update dataset files new form

- app/assets/stylesheets/application-redesign.css.scss
- app/assets/stylesheets/challenges/dataset_files.scss
- app/controllers/dataset_files_controller.rb
- app/controllers/dataset_folders_controller.rb
- app/helpers/files_helper.rb
- app/models/challenge.rb
- app/models/dataset_folder.rb
- app/policies/dataset_folder_policy.rb
- app/services/aws/fetch_dataset_files_service.rb
- app/views/dataset_files/_dataset_folder.html.erb
- app/views/dataset_files/_form.html.erb
- app/views/dataset_files/edit.html.erb
- app/views/dataset_files/index.html.erb
- app/views/dataset_folders/_form.html.erb
- app/views/dataset_folders/edit.html.erb
- app/views/dataset_folders/new.html.erb
- app/views/shared/challenges/_dataset_file.html.erb
- config/routes.rb
- db/migrate/20200509113731_rename_dataset_files_endpoint_to_region.rb
- db/migrate/20200510140417_create_dataset_folders.rb
- db/migrate/20200510182517_remove_own_fields_from_dataset_files.rb
- db/schema.rb
- spec/factories/dataset_folder_factory.rb
- spec/services/aws/fetch_dataset_files_service_spec.rb
- spec/vcr/aws_api/fetch_dataset_files/failure.yml
- spec/vcr/aws_api/fetch_dataset_files/success.yml
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/546476740
https://aicrowd.monday.com/boards/363093650/pulses/546487031
> Add dataset folders functionality

- Gemfile
- Gemfile.lock
- config/initializers/puma_worker_killer.rb
- config/puma.rb
Based on:
https://github.com/evanphx/puma-heroku/blob/master/lib/puma/plugin/heroku.rb
> Reduce web server memory usage 

- app/views/participants/_tooltip_profile.html.erb
> if ranking -1 ranking not applicable

- app/controllers/challenges_controller.rb
fix the reorder page to start from 1 as well
https://aicrowd.monday.com/boards/363093650/pulses/559048413
> Set new order from 1

- app/assets/stylesheets/application-redesign.css.scss
- app/views/shared/challenges/_listing.html.erb
- app/views/shared/challenges/_masthead_extra.html.erb
- app/views/shared/challenges/_team_stat.html.erb
> Fix space after teams count

- app/javascript/stimulus_js/controllers/challenges_controller.js
- app/views/challenges/fields/_submit_buttons.html.erb
> Warn admin on updating rules

- app/admin/challenge.rb
> Fix challenge edit link

- app/controllers/api/v1/challenges/dataset_files_controller.rb
- app/serializers/api/v1/dataset_file_serializer.rb
- config/routes.rb
- spec/requests/api/v1/challenges/dataset_files_controller_spec.rb
- spec/serializers/api/v1/dataset_file_serializer_spec.rb
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/546487201
> Add Api::V1::DatasetFiles#create #update and #destroy endpoints

- app/controllers/api/v1/challenges/dataset_folders_controller.rb
- app/helpers/images_helper.rb
- app/serializers/api/v1/dataset_folder_serializer.rb
- config/routes.rb
- db/schema.rb
- spec/requests/api/v1/challenges/dataset_folders_controller_spec.rb
- spec/serializers/api/v1/dataset_folder_serializer_spec.rb
- spec/services/aws/fetch_dataset_files_service_spec.rb
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/546487201
> Add DatasetFolder#create #update and #destroy endpoints

- app/controllers/practice_controller.rb
- app/views/layouts/_header.html.erb
- app/views/practice/index.html.erb
- app/views/practices/index.html.erb
- app/views/shared/challenges/_listing_compact.html.erb
- config/routes.rb
update url from /pratices to /practice
> Update practices route to practice

- app/admin/challenge.rb
- app/controllers/practice_controller.rb
- app/views/practice/index.html.erb
- app/views/practice/index.js.erb
- app/views/shared/challenges/_listing_compact.html.erb
- spec/controllers/practice_controller_spec.rb
Practice Index : Load more feature and add controller spec
> Auto load more practices and add spec

- app/assets/stylesheets/participants/activity_heatmap.scss
- app/controllers/participants_controller.rb
- app/helpers/graphs_helper.rb
- app/javascript/stimulus_js/controllers/activity_heatmap_controller.js
- app/views/participants/show.html.erb
- package.json
- yarn.lock
> Implement activity heatmap feedback

- app/assets/stylesheets/application-redesign.css.scss
- app/views/practice/index.html.erb
> Set heading for practice editors selection

- app/admin/challenge.rb
- app/helpers/active_admin/views_helper.rb
- app/models/challenge.rb
> Fix challenge edit link on admin challenge index

- app/controllers/challenge_rules_controller.rb
- app/models/participant_organizer.rb
Rollbar:
https://rollbar.com/aicrowd-production/aicrowd-production/items/345/
> Return 404 not found page when challenge rules are missing

- app/controllers/dataset_files_controller.rb
- app/helpers/files_helper.rb
- app/views/dataset_files/_form.html.erb
Monday: 
https://aicrowd.monday.com/boards/363093650/pulses/569698480
> Add missing external_file_size field to dataset_files form

- app/controllers/members_controller.rb
Rollbar:
https://rollbar.com/aicrowd-production/aicrowd-production/items/369/
> Fix organisation new member form

- app/services/discourse/add_users_to_group_service.rb
Rollbar: 
https://rollbar.com/aicrowd-production/aicrowd-production/items/367/
> Don't raise error when users are already members of Discourse group

- app/models/challenge_round.rb
- app/views/leaderboards/_leaderboards.html.erb
- app/views/leaderboards/index.html.erb
Overloaded sort_order functionality to get it done
> Added option to hide secondary score in leaderboards

- app/assets/stylesheets/application-redesign.css.scss
> Bugfix: width of image and table in md-content rendering

- app/assets/stylesheets/application-redesign.css.scss
- app/helpers/challenges_helper.rb
- app/views/shared/challenges/_listing_compact.html.erb
- app/views/shared/challenges/_masthead_pills.html.erb
Set practice badge active or draft
> Set practice badge active or draft

- app/assets/stylesheets/application-redesign.css.scss
- app/views/submissions/_submissions.html.erb
- app/views/submissions/show.html.erb
Error display fix in submissions (trim from css and not rails side) + Show error in submission#show page
Mobile view :
> Truncate submission message

- app/views/participants/_challenge_list.html.erb
https://aicrowd.monday.com/boards/363093650/pulses/575387934
> Remove prizes information from challenges in user insights tab

- app/views/challenges/show_meta_challenge.html.erb
- app/views/insights/_charts/_challenge_participants_country.html.erb
- app/views/insights/_charts/_submissions_vs_time.html.erb
- app/views/insights/_charts/_top_score_vs_time.html.erb
- app/views/landing_page/index.html.erb
- app/views/participants/show.html.erb
- app/views/submissions/new/_choose.html.erb
https://aicrowd.monday.com/boards/363093650/pulses/572228198
> Remove decoration from section headers

- app/views/participants/_challenge_list.html.erb
- app/views/shared/challenges/_listing.html.erb
https://aicrowd.monday.com/boards/363093650/pulses/580698610
> Practice badge on profile and organizers challenge list

- app/controllers/participants_controller.rb
- app/views/participants/edit.html.erb
> Show error messages in Edit profile page

- app/services/aws/base_service.rb
Rollbar:
https://rollbar.com/aicrowd-production/aicrowd-production/items/376/
> Fix 5xx error when AWS credentials are not set

- app/views/shared/challenges/_masthead_extra.html.erb
> Fix challenge header

- app/controllers/dataset_files_controller.rb
- config/routes.rb
Rollbar:
https://rollbar.com/aicrowd-production/aicrowd-production/items/202/?item_page=0&#traceback
> Fix dataset_files#show missing template error

- app/controllers/clef_tasks_controller.rb
- app/controllers/concerns/dataset_files.rb
- app/controllers/dataset_files_controller.rb
- app/controllers/task_dataset_files_controller.rb
- app/helpers/participant_clef_tasks_helper.rb
- app/views/clef_tasks/_form.html.erb
- app/views/dataset_files/_dataset_files.html.erb
- app/views/dataset_files/index.html.erb
- app/views/task_dataset_files/index.html.erb
- app/views/task_dataset_files/resources/_participant_submitted.html.erb
- app/views/task_dataset_files/resources/_participant_unregistered.html.erb
- db/migrate/20200603151708_add_use_challenge_dataset_files_to_clef_tasks.rb
- db/schema.rb
> Allow to use challenge dataset files in CLEF challenge

- app/assets/images/img/award-bronze.svg
- app/assets/images/img/award-gold.svg
- app/assets/images/img/award-silver.svg
- app/assets/stylesheets/application-redesign.css.scss
- app/helpers/leaderboard_helper.rb
- app/models/participant.rb
- app/models/submission.rb
- app/models/team.rb
- app/views/leaderboards/_leaderboards.html.erb
- app/views/leaderboards/_participant_submission_graph.html.erb
- app/views/leaderboards/_winners.html.erb
- app/views/leaderboards/index.html.erb
> Add top three winners in leaderboards

- app/assets/stylesheets/application-redesign.css.scss
- app/helpers/participants_helper.rb
- app/jobs/discourse/update_permissions_job.rb
Rollbar:
https://rollbar.com/aicrowd-production/aicrowd-production/items/338
https://rollbar.com/aicrowd-production/aicrowd-production/items/378
> Fix recent Rollbar errors

- app/assets/javascripts/ckeditor/plugins/codesnippet/lib/highlight/styles/sunburst.css
https://github.com/AIcrowd/AIcrowd/issues/1523
> Change css of code block

- app/views/leaderboards/_leaderboards.html.erb
- app/views/leaderboards/_winners.html.erb
Rollbar:
https://rollbar.com/aicrowd-production/aicrowd-production/items/381/
> Fix OldParticipant bug

- app/views/admin/notifications_mailer/newsletter_email_notification_email.html.erb
> Add See all pending newsletters link to newsletter_email notification

- app/assets/images/img/icon-filter.svg
- app/assets/javascripts/controllers/leaderboards_controller.js
- app/assets/stylesheets/application-redesign.css.scss
- app/controllers/leaderboards_controller.rb
- app/helpers/leaderboard_helper.rb
- app/javascript/stimulus_js/controllers/leaderboards_controller.js
- app/lib/country.rb
- app/models/leaderboard/base_leaderboard.rb
- app/models/leaderboard/disentaglement_leaderboard.rb
- app/models/leaderboard/leaderboard.rb
- app/models/leaderboard/ongoing_leaderboard.rb
- app/models/participant.rb
- app/policies/leaderboard_policy.rb
- app/policies/ongoing_leaderboard_policy.rb
- app/services/leaderboards/filter_service.rb
- app/views/leaderboards/_filter_leaderboards.html.erb
- app/views/leaderboards/get_affiliation.js.erb
- app/views/leaderboards/index.html.erb
- config/routes.rb
- spec/lib/country_spec.rb
- spec/models/participant_spec.rb
- spec/policies/leaderboard_policy_spec.rb
- spec/policies/ongoing_leaderboard_policy_spec.rb
- spec/services/leaderboards/filter_service.rb
> Add leaderboard filters

- app/views/leaderboards/_filter_leaderboards.html.erb
> Hide post challenge toggle button

- app/assets/stylesheets/application-redesign.css.scss
> Revert "Minor CSS change for card-footer (organisers display)"

- app/controllers/leaderboards_controller.rb
- app/helpers/leaderboard_helper.rb
- app/views/leaderboards/_participant_submission_graph.html.erb
> Refactor submission trend codebase

- db/migrate/20200615135036_change_challenge_featured_sequence_default.rb
- db/schema.rb
https://aicrowd.monday.com/boards/363093650/pulses/594706241
> Fix featured sequence default value

- app/controllers/participants/omniauth_callbacks_controller.rb
- app/models/participant.rb
- config/initializers/devise.rb
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/569704896
Documentation:
https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#requested-scopes-and-granted-scopes
> Update github omniauth requested permissions

- app/assets/stylesheets/application-redesign.css.scss
- app/views/submissions/index.html.erb
https://aicrowd.monday.com/boards/363093650/pulses/609950649
> Fix infinite scroll issue for submissions

- app/policies/leaderboard_policy.rb
- app/policies/ongoing_leaderboard_policy.rb
- app/services/leaderboards/filter_service.rb
- spec/services/leaderboards/filter_service.rb
https://rollbar.com/aicrowd-production/aicrowd-production/items/396/
> Fix leaderboard filter query issue

- app/views/submissions/index.html.erb
> Fix submissions remaining message

- Gemfile
- Gemfile.lock
- config/environments/production.rb
- config/environments/staging.rb
Documentation:
https://devcenter.heroku.com/articles/building-a-rails-3-application-with-memcache
> Install dalli Memcache client

- app.json
Documentation:
https://www.postgresql.org/docs/9.2/app-pgrestore.html
> Fix review apps failing on foreign key constraints

- app/controllers/participants_controller.rb
- app/javascript/stimulus_js/controllers/notifications_controller.js
- app/models/challenge.rb
- app/models/notification.rb
- app/services/notification_service.rb
- app/views/layouts/_notifications_dropdown.html.erb
- db/migrate/20200616142418_add_challenge_to_notifications.rb
- db/schema.rb
https://aicrowd.monday.com/boards/363093650/pulses/610004882
> Notification feature : Feedback changes

- app/controllers/participants_controller.rb
Redirect only for HTML reuqest
> fix redirect JS issue

- app/views/members/_members.html.erb
> Fix organization member tooltip issue

- app/controllers/task_dataset_files_controller.rb
Rollbar:
https://rollbar.com/aicrowd-production/aicrowd-production/items/406/
> Fix TaskDatasetFilesController#index Rollbar error

- app/controllers/challenge_call_responses_controller.rb
- app/controllers/challenges_controller.rb
- app/controllers/clef_tasks_controller.rb
- app/controllers/organizers_controller.rb
- app/controllers/submissions_controller.rb
- app/controllers/task_dataset_files_controller.rb
- app/views/challenge_call_responses/_call_closed.html.erb
- app/views/challenge_call_responses/_call_open.html.erb
- app/views/challenge_problems/_form.html.erb
- app/views/challenge_rules/show.html.erb
- app/views/challenges/_form.html.erb
- app/views/challenges/newsletter_emails/new.html.erb
- app/views/clef_tasks/_form.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/organizers/_form.html.erb
- app/views/organizers/new.html.erb
- app/views/participants/edit.html.erb
- app/views/submissions/edit.html.erb
- app/views/submissions/new/_artifact.html.erb
- app/views/submissions/new/_clef_form.html.erb
- app/views/submissions/new/_code.html.erb
- app/views/task_dataset_files/_form.html.erb
- config/routes.rb
I'm already handling dataset_files and dataset_folders here:
https://github.com/AIcrowd/AIcrowd/pull/1588
> Fix missing forms errors across website

- app/helpers/application_helper.rb
- app/javascript/stimulus_js/controllers/notifications_controller.js
- app/views/layouts/_header.html.erb
- app/views/layouts/_notifications_dropdown.html.erb
- app/views/participants/read_notification.js.erb
https://aicrowd.monday.com/boards/363093650/pulses/619640173
> Fix notification bell icon issue

- app/admin/aicrowd_badges.rb
- app/admin/paper_trail/version.rb
- app/models/aicrowd_badge.rb
Added Papertrail Versioning for AIcrowd badges!
> Versioning feature added for badges

- app/jobs/discourse/upsert_user_job.rb
- app/models/participant.rb
- app/services/discourse/upsert_user_service.rb
- lib/tasks/discourse.rake
- spec/services/discourse/upsert_user_service_spec.rb
- spec/vcr/discourse_api/update_user/partcipant_does_not_exist_success.yml
- spec/vcr/discourse_api/update_user/partcipant_exists_success.yml
Issue #1204: Synchronise participant username with Discourse
Monday : https://aicrowd.monday.com/boards/363093650/pulses/546451555
Rake task:
- `bundle exec rake discourse:synchronize_participants_with_discourse`
> Synchronise participants with Discourse

- app/controllers/leaderboards_controller.rb
- db/migrate/20200630120007_change_base_leaderboard_baseline_default.rb
- db/migrate/20200630120421_update_leaderboards_to_version_24.rb
- db/migrate/20200630120601_change_disentanglement_leaderboard_baseline_default.rb
- db/migrate/20200630120822_update_ongoing_leaderboards_to_version_8.rb
- db/schema.rb
- db/views/leaderboards_v24.sql
- db/views/ongoing_leaderboards_v08.sql
- lib/tasks/update_baseline.rake
> Fix baseline condition

- app/services/discourse/api_client.rb
- app/services/discourse/base_service.rb
- app/services/discourse/create_category_service.rb
- spec/services/discourse/create_category_service_spec.rb
- spec/support/shared_examples/discourse_service_object_spec.rb
- spec/vcr/discourse_api/create/success_not_existing_username.yml
- spec/vcr/discourse_api/create/success_participant_username.yml
Monday: 
https://aicrowd.monday.com/boards/363093650/pulses/574264254
> Use organizer username as Discourse API username when creating topic

- app/assets/stylesheets/application-redesign.css.scss
- app/controllers/follows_controller.rb
- app/controllers/leaderboards_controller.rb
- app/controllers/participants_controller.rb
- app/helpers/follows_helper.rb
- app/helpers/participants_helper.rb
- app/models/follow.rb
- app/models/participant.rb
- app/views/follows/refresh.js.erb
- app/views/leaderboards/_filter_leaderboards.html.erb
- app/views/participants/_followers.html.erb
- app/views/participants/_following.html.erb
- app/views/participants/_masthead.html.erb
- app/views/participants/show.html.erb
- app/views/shared/challenges/_follow_button.html.erb
- app/views/shared/challenges/_masthead_extra.html.erb
- config/routes.rb
- spec/controllers/follows_controller_spec.rb
https://aicrowd.monday.com/boards/363093650/pulses/615742498
> N days of ML: friends-followers leaderboard

- app/models/participant.rb
- lib/tasks/participant_associative.rake
https://aicrowd.monday.com/boards/363093650/pulses/634019513
rake task to destroy participant associative records if participant does not exists anymore:
rake participant_associative:destroy
> Fix foreign key violation issue for participants

- app/services/discourse/base_service.rb
Rollbar:
https://rollbar.com/aicrowd-production/aicrowd-production/items/425/
> Don't raise error on Discourse::TooManyRequests error

- app/helpers/challenges_helper.rb
- app/views/shared/challenges/_dataset_file.html.erb
- app/views/shared/challenges/_listing.html.erb
- app/views/shared/challenges/_masthead_pills.html.erb
----Minor tooltip additions----
Added end time tooltip to pills:
Added eyeslash icon :
> Added Minor tooltip additions

- app/views/insights/index.html.erb
Rollbar:
https://rollbar.com/aicrowd-production/aicrowd-production/items/437/
> Handle nil exception in Blitz challenge insights tab

- app/views/insights/index.html.erb
Rollbar:
https://rollbar.com/aicrowd-production/aicrowd-production/items/437/?item_page=0&#traceback
> Fix insights tabs nil exception

- app/models/concerns/freeze_record.rb
- app/views/leaderboards/index.html.erb
Fix Freeze Leaderboard for blank submission index and blank challenge_round.
> quick fix of freeze leaderboard

- app/javascript/stimulus_js/controllers/challenge_overview_controller.js
- app/javascript/stimulus_js/controllers/challenges_edit_controller.js
- app/javascript/stimulus_js/controllers/linkify_content_controller.js
- app/views/challenge_rules/show.html.erb
- app/views/submissions/_submissions.html.erb
- app/views/submissions/show.html.erb
- package.json
- yarn.lock
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/634740869
https://aicrowd.monday.com/boards/363093650/pulses/634697985
> Linkify links in challenge Overview tab, submissions and challenge rules

- app/controllers/api/v1/base_controller.rb
- app/controllers/api/v1/organizers_controller.rb
- app/serializers/api/v1/organizer_serializer.rb
- config/routes.rb
- spec/requests/api/v1/organizers_controller_spec.rb
- spec/serializers/api/v1/organizer_serializer_spec.rb
Monday: 
https://aicrowd.monday.com/boards/363093650/pulses/635764720
Postman documentation link is inside Monday ticket.
> Add Api::V1::Organizers#create and #update endpoints

- app/controllers/leaderboards_controller.rb
https://aicrowd.monday.com/boards/363093650/pulses/644084787
Show outgoing record to organizer in case of freeze_round
> Issue : Leaderboard not showing for login user

- app/jobs/gitlab/update_username_job.rb
- app/models/participant.rb
- app/services/gitlab/api_client.rb
- app/services/gitlab/base_service.rb
- app/services/gitlab/fetch_calendar_activity_service.rb
- app/services/gitlab/fetch_user_by_external_id_service.rb
- app/services/gitlab/update_username_service.rb
- config/application.yml.example
- config/sidekiq.yml
- db/migrate/20200708225717_add_gitlab_id_to_participants.rb
- db/schema.rb
- spec/rails_helper.rb
- spec/services/gitlab/fetch_calendar_activity_service_spec.rb
- spec/services/gitlab/fetch_user_by_external_id_service_spec.rb
- spec/services/gitlab/update_username_service_spec.rb
- spec/support/config/vcr.rb
- spec/support/shared_examples/gitlab_service_object_spec.rb
- spec/vcr/gitlab_api/fetch_user_by_external_id/success.yml
- spec/vcr/gitlab_api/fetch_user_by_external_id/user_not_found.yml
- spec/vcr/gitlab_api/update_username/success.yml
- spec/vcr/gitlab_api/update_username/user_not_found.yml
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/634427504
> Synchronise AICrowd username with Gitlab

- app/controllers/participants/registrations_controller.rb
- app/javascript/stimulus_js/controllers/landing_page_controller.js
- app/javascript/stimulus_js/controllers/registration_form_controller.js
- app/models/participant.rb
- app/views/devise/registrations/new.html.erb
- app/views/landing_page/index.html.erb
- db/migrate/20200714084414_add_uuid_to_participants.rb
- db/migrate/20200714101759_add_referred_by_id_to_participants.rb
- db/schema.rb
- spec/features/participants/registrations_controller_spec.rb
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/644618203
Example usage:
https://aicrowd-staging.herokuapp.com/?referred_by_uuid=e82f23b2-f350-4bd1-af57-fe8cafe1bfc7
> Simple referral functionality for landing page

- app/controllers/api/v1/organizers/organizers_controller.rb
- app/controllers/api/v1/organizers/participant_organizers_controller.rb
- app/serializers/api/v1/organizer_serializer.rb
- app/serializers/api/v1/participant_serializer.rb
- config/routes.rb
- spec/requests/api/v1/organizers/organizers_controller_spec.rb
- spec/requests/api/v1/organizers/participant_organizers_controller_spec.rb
- spec/serializers/api/v1/organizer_serializer_spec.rb
- spec/serializers/api/v1/participant_serializer_spec.rb
Monday: 
https://aicrowd.monday.com/boards/363093650/pulses/646438688
> Add Api::V1::Organizers#show endpoint

- app/services/notification_service.rb
https://aicrowd.monday.com/boards/363093650/pulses/634024839
> Fix notification message for leaderboard

- app/controllers/application_controller.rb
- app/controllers/participants_controller.rb
- app/models/participant.rb
- app/views/participants/edit.html.erb
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/634476770
> Limit Participant.name to 20 characters

- app/assets/javascripts/modules/direct_s3_upload.js
- app/views/leaderboards/_leaderboards.html.erb
- app/views/shared/challenges/_dataset_file.html.erb
- spec/features/task_dataset_files_controller_spec.rb
Rollbar:
https://rollbar.com/aicrowd-production/aicrowd-production/items/359/
https://rollbar.com/aicrowd-production/aicrowd-production/items/320/
https://rollbar.com/aicrowd-production/aicrowd-production/items/383/
> Fix recent Rollbar bugs

- app/controllers/searches_controller.rb
- app/helpers/follows_helper.rb
- app/helpers/search_helper.rb
- app/javascript/stimulus_js/controllers/search_controller.js
- app/javascript/stimulus_js/controllers/search_form_controller.js
- app/views/layouts/_header.html.erb
- app/views/searches/show.html.erb
- config/routes.rb
- spec/features/searches_controller_spec.rb
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/634423939
> Add side wide search functionality for challenges and participants

- app/admin/feedback.rb
- app/assets/stylesheets/_feedback.scss
- app/assets/stylesheets/application-redesign.css.scss
- app/controllers/api/v1/feedbacks_controller.rb
- app/javascript/stimulus_js/controllers/feedback_form_controller.js
- app/javascript/stimulus_js/helpers/alerts_helper.js
- app/mailers/feedback_mailer.rb
- app/models/feedback.rb
- app/serializers/api/v1/feedback_serializer.rb
- app/views/feedback_mailer/feedback_email.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_feedback_modal.html.erb
- config/routes.rb
- db/migrate/20200722115821_create_feedbacks.rb
- db/schema.rb
- spec/factories/feedback_factory.rb
- spec/mailers/feedback_mailer_spec.rb
- spec/requests/api/v1/feedbacks_controller_spec.rb
- spec/serializers/api/v1/feedback_serializer_spec.rb
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/634759386
> Add Feedback button to website

- app/controllers/challenges_controller.rb
- app/helpers/challenges_helper.rb
- app/models/challenge.rb
- app/models/challenge_problems.rb
- app/views/shared/challenges/_masthead_extra.html.erb
- app/views/shared/challenges/_team_stat.html.erb
- spec/factories/challenge_factory.rb
- spec/factories/challenge_problem_factory.rb
- spec/helpers/challenges_helper_spec.rb
Monday: 
https://aicrowd.monday.com/boards/363093650/pulses/649651556
> Fix challenge statistics in challenge masthead

- app/views/leaderboards/_leaderboards.html.erb
- app/views/leaderboards/index.html.erb
Monday: 
https://aicrowd.monday.com/boards/363093650/pulses/634703316
> Text align right scores in leaderboards table

- app/services/discourse/fetch_search_results_service.rb
Rollbar:
https://rollbar.com/aicrowd-production/aicrowd-production/items/454/
> Return empty Discourse search results collection when query parameter blank

- app/controllers/api/v1/challenges/challenge_rounds_controller.rb
- app/controllers/challenges_controller.rb
- app/controllers/submissions_controller.rb
- app/models/challenge_round.rb
- app/views/challenges/fields/_challenge_round_fields.html.erb
- app/views/submissions/new.html.erb
- app/views/submissions/new/_artifact.html.erb
- app/views/submissions/new/_clef_form.html.erb
- app/views/submissions/new/_code.html.erb
- db/migrate/20200723090532_add_submmission_type_to_challenge_rounds.rb
- db/schema.rb
- lib/tasks/challenges.rake
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/634744003
Rake task:
`bundle exec rake challenges:update_challenge_rounds_submissions_type`
> Add submissions_type field to challenge_rounds form

- app/queries/submissions_remaining_query.rb
- spec/queries/submissions_remaining_query_spec.rb
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/666070493
> Update SubmissionsRemainingQuery to take participant team into account

- app/helpers/challenges_helper.rb
- app/models/challenge.rb
- app/views/challenges/show/_sidenav.html.erb
- app/views/challenges/show_meta_challenge.html.erb
- app/views/practice/index.html.erb
- app/views/practice/index.js.erb
- app/views/shared/challenges/_listing_compact.html.erb
- spec/helpers/challenges_helper_spec.rb
> Fix challenge statistics

- app/controllers/leaderboards_controller.rb
- app/services/challenge_rounds/create_leaderboards_service.rb
- app/views/leaderboards/_leaderboards.html.erb
- app/views/leaderboards/_winners.html.erb
- db/migrate/20200727145621_add_old_participant_id_to_base_leaderboards.rb
- db/schema.rb
- lib/tasks/leaderboards.rake
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/634484427
Rake task:
`bundle exec rake leaderboards:migrate_old_partcipants_submitter_id_to_old_participant_id`
> Remove OldParticipant references in code and database but keep data

- app/jobs/discourse_badges_daily_job.rb
https://rollbar.com/app119736017-heroku.com/app119736017-heroku.com/items/67/
> Check response is Array

- app/controllers/leaderboards_controller.rb
Export Freeze record in the leaderboard CSV
> Export Ongoing Leaderboard

- app/views/submissions/show.html.erb
This reverts commit eeb94f77bfd09d7d613d304802738c131574a1e3.
> Revert "Organisers can view private score in submission details page"

- app/controllers/challenges_controller.rb
- app/controllers/leaderboards_controller.rb
- app/helpers/tabs_helper.rb
- app/jobs/calculate_leaderboard_job.rb
- app/models/challenge.rb
- app/models/challenge_leaderboard_extra.rb
- app/services/challenge_rounds/create_leaderboards_service.rb
- app/views/challenges/tabs/_admin_form.html.erb
- app/views/leaderboards/index.html.erb
- db/migrate/20201019142234_create_challenge_leaderboard_extras.rb
- db/migrate/20201020080136_add_challenge_leaderboard_extra_id_to_base_leaderboard.rb
- db/migrate/20201020095311_update_leaderboards_to_version_26.rb
- db/migrate/20201020095520_update_ongoing_leaderboards_to_version_10.rb
- db/views/leaderboards_v26.sql
- db/views/ongoing_leaderboards_v10.sql
> Multi-track leaderboards implementation, dynamically filtered

- app/helpers/media_helper.rb
- app/views/shared/challenges/_media.html.erb
> fixes video autoplay on leaderboard

- app/controllers/challenges_controller.rb
- app/controllers/leaderboards_controller.rb
- app/policies/challenge_policy.rb
- app/views/leaderboards/index.html.erb
- app/views/leaderboards/index.js.erb
> pin user rank on challenges leaderboard

- app/mailers/admin/notifications_mailer.rb
- app/mailers/newsletter_emails_mailer.rb
> add reply_to in newsletter emails

- app/views/email_preferences/_header.html.erb
- app/views/layouts/_header.html.erb
- app/views/participants/_header.html.erb
- app/views/participants/edit.html.erb
> merged edit profile and Account Settings into one

- app/assets/stylesheets/_notebook.scss
- app/assets/stylesheets/application-redesign.css.scss
- app/assets/stylesheets/commontator/application.scss
- app/helpers/posts_helper.rb
- app/javascript/stimulus_js/controllers/post_controller.js
- app/models/commontator_comment.rb
- app/models/submission.rb
- app/views/commontator/comments/_form.html.erb
- app/views/commontator/comments/_show.html.erb
- app/views/commontator/subscriptions/_link.html.erb
- app/views/commontator/threads/_show.html.erb
- app/views/posts/show.html.erb
- app/views/shared/posts/_post_list.html.erb
- app/views/shared/votes/_button.html.erb
- config/initializers/commontator.rb
- config/routes.rb
- db/migrate/20210123225305_add_vote_count_to_commontator_comments.rb
Contributions
- Show more button
- List of users who have liked
- Votable comments
Submissions
- RandomHex increased to 12 instead of 6
- Disabled badges computation
- Kramdown on submissions grading message
> Community Contributions changes, Submission Message Kramdown

- app/assets/stylesheets/application-redesign.css.scss
- app/views/submissions/_submissions.html.erb
- app/views/submissions/show.html.erb
- spec/requests/api/external_graders_controller/external_graders_controller_PATCH_spec.rb
- spec/requests/api/external_graders_controller/external_graders_controller_POST_spec.rb
> Test case fixes due to recent changes

- app/assets/stylesheets/application-redesign.css.scss
- app/controllers/challenges_controller.rb
- app/helpers/tabs_helper.rb
- app/views/challenges/notebooks.html.erb
- app/views/landing_page/index.html.erb
- app/views/participants/_articles_list.html.erb
- app/views/participants/show.html.erb
- app/views/posts/index.html.erb
- config/routes.rb
> Added remaining changes for branding changes

- app/jobs/calculate_leaderboard_job.rb
Minor changes to enable multiple leaderboard in meta challenges
> Enable multiple leaderboard in meta challenges

- app/controllers/submissions_controller.rb
- app/models/submission.rb
- app/policies/challenge_policy.rb
- app/views/challenges/tabs/_misc_form.html.erb
- app/views/submissions/edit.html.erb
- config/routes.rb
- db/migrate/20210310094941_add_column_deleted_to_submission.rb
> Submission deletion option

- app/controllers/submissions_controller.rb
- app/views/submissions/edit.html.erb
- app/views/submissions/show.html.erb
- app/views/submissions/tabs/_summary.html.erb
- Video rendering fix
- Submitted by users list on top right
> Submissions page improvements

- app/controllers/posts_controller.rb
- app/javascript/stimulus_js/controllers/post_controller.js
- app/services/notebooks/notebook_base_service.rb
- app/services/notebooks/notebook_file_service.rb
- app/services/notebooks/submission_notebook_service.rb
- app/views/posts/_post_form.html.erb
- config/routes.rb
https://user-images.githubusercontent.com/19958882/115573707-a0413700-a2de-11eb-9218-0a07c25a1633.mov
> added notebook upload option in community contribution

- app/controllers/challenges_controller.rb
- app/controllers/submissions_controller.rb
- app/views/challenges/tabs/_private_challenge_form.html.erb
- db/migrate/20210423160025_add_restricted_ips_to_challenges.rb
- db/schema.rb
> added restricted ip for a challenge

- Gemfile
- Gemfile.lock
- app/admin/dashboard.rb
- app/controllers/application_controller.rb
- app/controllers/participants_controller.rb
- app/controllers/submissions_controller.rb
- app/models/active_admin_participant_authorization.rb
- app/views/leaderboards/index.html.erb
- app/views/participants/show.html.erb
- app/views/submissions/show.html.erb
- config/initializers/active_admin.rb
- config/initializers/doorkeeper.rb
- config/routes.rb
- db/migrate/20210526120128_add_super_admin_to_participants.rb
- db/schema.rb
> Hotfix deploy

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/challenge_participants_controller.rb
- app/controllers/participants/omniauth_callbacks_controller.rb
- app/controllers/participants/registrations_controller.rb
- app/controllers/participants_controller.rb
- app/javascript/stimulus_js/controllers/mixpanel_controller.js
- app/jobs/mixpanel/event_job.rb
- app/jobs/mixpanel/sync_job.rb
- app/models/participant.rb
- app/views/challenges/show/_sidenav.html.erb
- app/views/challenges/show/_subnav.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/layouts/_header.html.erb
- app/views/layouts/_mixpanel.html.erb
- app/views/layouts/application.html.erb
- config/initializers/mixpanel.rb
- db/migrate/20210228073542_add_mixpanel_done_to_participants.rb
- package.json
- yarn.lock
Mixpanel setup, Mixpanel ruby jobs implementation, Mixpanel browser initial work by @skbly7 
Fix mixpanel jobs, fix login/registration and participation flow by @chittalpatel 
- Track anonymous users (not signed in)
- Track page visits
- Track login/registration flow
- Track challenge participation flow
> Mixpanel integration

- app/controllers/participants/omniauth_callbacks_controller.rb
- Fix `Registration complete` event job
> [fix] `Registration Complete` event job

- app/controllers/participants/omniauth_callbacks_controller.rb
- app/controllers/participants/sessions_controller.rb
- app/controllers/participants_controller.rb
- app/jobs/mixpanel/sync_job.rb
- app/models/participant.rb
- config/routes.rb
- Add custom Participants::SessionsController to send ip of the request with Mixpanel user profile set event to resolve user location
> Resolve location for user profile set event

- app/javascript/stimulus_js/controllers/leaderboards_controller.js
- app/views/leaderboards/_filter_leaderboards.html.erb
- Add challenge_leaderboard_extra_id to build filter queries
> Fix leaderboard filter bug for multiple leaderboards

- app/views/shared/challenges/_listing_compact.html.erb
- Don't show draft challenges publicly under meta challenge and show a `Hidden` badge to Admins/Organizers for such challenges
> Update meta challenge cards visibility

- app/controllers/pages_controller.rb
- app/views/layouts/_footer.html.erb
- app/views/pages/community_guidelines.erb
- config/routes.rb
- db/schema.rb
- Added community guidelines page for the route: `/community_guidelines`, also added its link in the legal section of footer
> Add community_guidelines page

- app/assets/stylesheets/application-redesign.css.scss
- app/assets/stylesheets/index.scss
- app/assets/stylesheets/publications/publication.css
- app/views/challenges/discussions/show.html.erb
- app/views/challenges/show_meta_challenge.html.erb
- app/views/insights/_charts/_challenge_participants_country.html.erb
- app/views/posts/show.html.erb
- app/views/publications/_filter.html.erb
- app/views/publications/all.html.erb
- app/views/publications/show.html.erb
- app/views/submissions/new/_artifact.html.erb
- app/views/submissions/new/_code.html.erb
Updated Frontend Bugs on homepage & other pages :
https://docs.google.com/document/d/1cpdesCTE5vNXvZy2U8A5vBvscA14LMHrrmxN55kNBCQ/edit?usp=sharing
> Frontend Fixes Added

- app/assets/stylesheets/application-redesign.css.scss
- app/views/participants/_tooltip_profile.html.erb
- app/views/posts/show.html.erb
- app/views/shared/_login_signup.html.erb
https://docs.google.com/document/d/1cpdesCTE5vNXvZy2U8A5vBvscA14LMHrrmxN55kNBCQ/edit?usp=sharing
> Minor Fixes AIcrowd

- app/views/shared/_login_signup.html.erb
Bug: Signups were getting tracked under login events.
> fix(mixpanel): Incorrect signups tracking
