app/models/participant.rb, spec/models/participant_spec.rb
My apologies I should have caught this in the PR, the new regex does not support numbers and I don't think that was intended.
=> add numbers to regex for participant handle

app/helpers/submissions_helper.rb, app/views/submissions/_submission.html.erb
quickest way to safely enable links.  We could also make this a markdown field but that would require adding a field to the submission table and also modifying the grader code which is generating this message.
=> enable-links-in-grading-messages

app/models/participant.rb
Make sure that Blogs are nullified and challenge_participant objects are destroyed when a participant is deleted
=> Participant Model: Fix destroy

app/controllers/api/external_graders_controller.rb, spec/requests/api/external_graders_controller/external_graders_controller_POST_spec.rb
When raising NoSubmissionSlotsRemaining, also pass the info
for when the next submission can be made.
Also small typo fix.
Closes https://github.com/AIcrowd/AIcrowd/issues/843
=> External API: Add reset time for when no slots remaining

app/views/challenges/index.html.erb, config/environments/production.rb
Haven't been able to test this, apart from the CI, and have just made the changes directly in the GitHub code editor, so please check.
- Fixes: https://github.com/AIcrowd/AIcrowd/issues/956
- Addresses: https://github.com/AIcrowd/AIcrowd/issues/909
- Removed a broken ```</main>``` tag which did not have an opening parent.
- Deleted empty ERB file and removed unused call to challenge subnav cell (in fact it was rendering it but rendering nothing)
As a general recommendation I'd consider moving away from Trailblazer cells ... they have deviated from Rails too much and are no longer well-supported. Hit me up if you want some thoughts on how to do this.
I'd also recommend putting the paging in now, perhaps using [StimulusJS](https://stimulusjs.org/) as it is Rails-friendly and perfect for …
=> Fix broken ERB closing tag

app/concepts/challenge/cells/statistic.rb, app/controllers/participant_challenges_controller.rb, app/jobs/update_challenge_stats_job.rb, app/views/leaderboards/index.html.erb
Removed the SQL job and using challenge.challenge_participants
for the count. Also showing all the challenge_participants
on the participants tab instead of the ones that accepted
only the latest terms.
Fixes https://github.com/AIcrowd/AIcrowd/issues/958
=> Fix count for participants, and show post-challenges switch for completed challs only

config/routes.rb, spec/controllers/teams_controller_spec.rb, spec/controllers/teams_invitations_controller_spec.rb, spec/factories/team_factory.rb
Modified the routes to allow for dotted names in `teams#show` and `team_invitations#create`
add tests for those routes (for both standard and dotted names)
change team factory to make first participant the team organizer
=> [HOTFIX] working teams pages where names contain dots

app/controllers/challenges/team_invitations_controller.rb
Right now if there are 2 teams both named A for 2 challenge
C1 and C2, then the invitation controller needs to select the
correct Team object for the respective challenge instead of
searching teams by name.
=> Team Invitations Controller: Set team from challenge

app/views/clef_tasks/index.html.erb, app/views/clef_tasks/show.html.erb, app/views/organizers/_subnav.html.erb, db/schema.rb
@nemaniarjun 
Discovered a bug where ordinary participants were able to see the dataset files on the organizer page, even whey they did not sign an EUA. This has been fixed now.
This PR can be safely merged, only changed permissions in some clef_specific views.
=> Fix permission issue for CLEF tasks when on organizer page

app/assets/javascripts/controllers/challenges_controller.js, app/assets/stylesheets/application-redesign.css.scss, app/assets/stylesheets/challenges/form.scss, lib/tasks/challenges.rake
This PR has the final changes required for merging CK editor for production:
1. Changes to TOC generation
2. Changes to CSS for md-content h1 -> h2, h2 -> h3 ... 
3. Rake task to update all the existing challenge description headings, h1 -> h2, h2 -> h3 ... 
4. Update to the min-width of the editor to match that of the overview page.
=> CK Editor: Small fixes, Rake Tasks

app/admin/participant.rb
Reason:
- [#1210] Current view is broke, and it is one of most important listing which we use.
- We dont use "organisers" column or edit participant for organiser via this ActiveAdmin ever.
=> Removed organiser details from Participants ActiveAdmin

app/javascript/stimulus_js/controllers/chart_controller.js, app/views/insights/_charts/_submissions_vs_time.html.erb, app/views/insights/_charts/_top_score_vs_time.html.erb
Added the Axis Labels for the 2 charts that we are rendering. 
Also found a bug where the score-dropdown was not showing for challenges with only 1 round. 
We need to ensure that all combinations work
1. Single Round Single Score
2. Single Round 2 scores
3. Multiple Rounds all Single score
4. Multiple Rounds all with 2 scores
5. Multiple Rounds with Single for some and 2 scores for some
I have tested locally for the above.
@spMohanty can you help test this out? Are there any other changes needed for the challenge insights page in the current version?
=> Insights: Add Axis Titles + Bug Fix for single round score dropdown

Gemfile, Gemfile.lock
- Removes duplicates from the gemfile
- Uses fog-aws metagem instead of aws which installs a lot of metagems
- Moves rails-assets to a separate source block
=> Gemfile: Fix dups & simplify

Gemfile, Gemfile.lock
sidekiq-unique-jobs 6.0.15 gem was unpublished on rubygems.org. We need to update it:
https://rubygems.org/gems/sidekiq-unique-jobs/versions
=> Update sidekiq-unique-jobs gem because 6.0.15 version was unpublished

app/assets/stylesheets/application-redesign.css.scss
=> Capitalise links in table of content

app/javascript/stimulus_js/controllers/challenge_overview_controller.js
* We no longer require "Updates" section after moving back from tab -> one page rendering
* Margin top needed to change only for first h2 and not all. (and mt-2 not mt-0)
* User friendly URLs in TOC going forward
=> Minor fix for overview h2 and toc rendering

app/assets/javascripts/controllers/challenges_controller.js, app/services/challenges/filter_service.rb, app/views/shared/challenges/_filter.html.erb, spec/services/challenges/filter_service_spec.rb
Issue : Currently, when I click on text of any challenge filter, modal popup of filter box will close.
Issue : If a challenge have 2 tag and I apply filtered on both, than challenge will appear twice.
Fixed it in this PR.
=> Fixes on Challenge filter

.travis.yml
This is only wasting our time on CircleCI, as nobody cares about those checks.
We need to configure CodeClimate for linting of Ruby code.
=> Remove Rubocop checks from Travis

app/views/shared/challenges/_listing.html.erb, app/views/shared/challenges/_masthead.html.erb
Filter URL were getting disturbed due to category tags.
=> Fix category tags

app/jobs/discourse/add_users_to_group_job.rb, app/jobs/discourse/create_category_job.rb, app/jobs/discourse/update_permissions_job.rb, app/models/challenge.rb, app/models/challenge_participant.rb, app/models/challenges_organizer.rb, app/models/participant_organizer.rb, app/services/discourse/add_users_to_group_service.rb, app/services/discourse/base_service.rb, app/services/discourse/create_category_service.rb, app/services/discourse/create_group_service.rb, app/services/discourse/update_category_service.rb, db/migrate/20200422223340_add_discourse_group_name_to_challenges.rb, db/schema.rb, lib/tasks/discourse.rake, spec/services/discourse/add_users_to_group_service_spec.rb, spec/services/discourse/create_group_service_spec.rb
Monday:
https://aicrowd.monday.com/boards/363093650/pulses/523058243
Rake tasks:
`bundle exec rake discourse:hide_discourse_categories_for_hidden_challenges`
`bundle exec rake discourse:add_challenge_participants_to_discourse_groups`
=> Hide discourse category when challenge is draft or private

config/initializers/evaluations_api.rb
We need to live with ssl_verify=false for now, the endpoint we are hitting doesn’t have stable HTTPS cert right now.
=> Undo removal of verify_ssl=False, the endpoint is not yet stable

app/assets/stylesheets/application-redesign.css.scss
This is done because keeping height restriction is causing participants names to be hidden in Firefox/Chrome and we don't really care about height in truncate thing, but just the width.
=> Removed height value in truncate class

app/views/landing_page/index.html.erb, app/views/layouts/_header.html.erb, app/views/participants/_masthead.html.erb, spec/features/challenges/participant_challenge_spec.rb
Both the feature needs stability, design/rendering fixes, and some more love before we expose them to end-users.
=> Hide badge reputation on participant masthead & link to leaderboards

app/helpers/challenges_helper.rb, app/models/challenge.rb, app/views/challenges/tabs/_details_form.html.erb, db/migrate/20200507094530_change_challenge_default.rb, db/schema.rb, lib/tasks/update_featured_sequence.rake
Features Challenge ordering should not be affected by new challenge creations (etc)
Monday : https://aicrowd.monday.com/boards/363093650/pulses/546915993
Run `rake update_featured_sequence:increase_by_one`
=> Set default 1 for challenge featured_sequence

app/helpers/media_helper.rb, app/views/shared/challenges/_media.html.erb
fix thumb media-content-type for leaderboard and submission.
For test : https://aicrowd-fix-thumb-media-4pibop.herokuapp.com/challenges/neurips-2019-minerl-competition/leaderboards
Here first submission has image thumb and video as media.
but on staging I can't get AWS video and images.
let me know other way to set video media.
=> set thumb media content type

app/assets/stylesheets/application-redesign.css.scss, app/views/leaderboards/_leaderboards.html.erb, app/views/submissions/edit.html.erb, app/views/submissions/show.html.erb
Baselines look as follow on leaderboard:
Challenge edit page (still hacky and needs work, but before/after is as below, more usable for time being)
Before
After
=> Bringing back baseline submission entries back to life

app/controllers/challenges_controller.rb, app/helpers/challenges_helper.rb, app/models/category.rb, lib/tasks/categories.rake
1. The rake task is to remove all the existing categories with prefixed hash.
2. Command to remove all existing prefixed hash categories through the rake task is `rake category:remove_prefixed_hash_from_categories`.
=> Fix prefixed hash category filter issue

app/services/terminate_challenges.rb
https://aicrowd.monday.com/boards/363093650/pulses/589241471
The issue was in services/terminate_challenges.rb because in existing code featured_sequence is getting updated with value 0 in same file and there is a validation for featured_sequence in challenge model for 0 value.
=> Fix challenge status filter issue

app/assets/stylesheets/application-redesign.css.scss
=> Minor CSS change for card-footer (organisers display)

app/models/concerns/polymorphic_submitter.rb, app/services/notification_service.rb, lib/tasks/remove_notification.rake
run rake task to delete notification of leaderboard that don't have `show_leaderboard?` permission
`rake remove_notification:leaderbaord_is_not_for_show`
This rake task also delete notification that's leaderboard is not exist in DB.
=> Prevent to create notification with existing notfication message

app/services/calculate_meta_leaderboard_service.rb
`seq` has been discontinued after new leaderboard calculation logic addition, hence moving the logic on `row_num` instead of `seq`
=> Start using row_num instead of seq for meta leaderboard

app/controllers/submissions_controller.rb
Add ".c" and ".cpp" file extensions to the list of allowed submissions. (will be used in OJ submissions coming from AIcrowd Classroom
=> Add c and cpp to allowed submission extensions

app/admin/aicrowd_badges.rb
Currently accessing https://www.aicrowd.com/admin/aicrowd_badges is giving 500 error as pulling paper trail versions for all the badges is taking more than 18ms.
ActiveAdmin pulls all the versions for the badges for the purpose of filtering, we don't need a filter based on versioning so removed it.
=> fixing 500 error on aicrowd badges admin

app/jobs/notification/leaderboard_notification_job.rb
The leaderboard notifications are bit dynamic in nature, and use existing notifications, previous and current ranks, to decide the best notification to show.
Unfortunately after multi-leaderboard implementation, these checks got messed up.
And it ultimately led to ranks comparison of position A on Leaderboard X with position B on Leaderboard Y.
This commit should solve such cases, and we will be only using default leaderboard standings for the notifications. The hypothesis is the default one is generally the most important standings.
=> Bugfix: Only use current/default leaderboard for notification generation

app/controllers/participants/registrations_controller.rb
- Return from `registration_callback_controller` if user can't be created
=> [fix] SerializationError for Mixpanel EventJob in `registration_controller_callback`
